[build]
  publish = "build/"
  command = "npm run build"
[[redirects]]
  from = "https://mantle.alley.co/*"
  to = "https://mantle.alley.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/testing-started/test-framework.html"
  to = "/docs/testing"
  status = 301
  force = true
[[redirects]]
  from = "/docs/next/models/querying-models"
  to = "/docs/next/models/query-builder"
  status = 301
  force = true
[[redirects]]
  from = "/docs/models/querying-models"
  to = "/docs/models/query-builder"
  status = 301
  force = true